name: Package openhrp3

# This workflow only runs when pushing to master
#
# It will:
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact-head
# - Upload the packages to https://dl.bintray.com/gergondet/multi-contact
#

on:
  repository_dispatch:
    types:
    - package
  push:
    branches:
      - debian

jobs:
  # This job build binary packages for Ubuntu
  build-packages:
    strategy:
      fail-fast: false
      matrix:
        dist: [xenial, bionic, focal]
        arch: [i386, amd64]
        exclude:
          - dist: focal
            arch: i386
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      if: github.event.action != 'package'
    - uses: actions/checkout@v1
      with:
        ref: 'debian'
      if: github.event.action == 'package'
    - name: Build package
      uses: jrl-umi3218/github-actions/build-package-native@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        other-mirrors: "https://dl.bintray.com/gergondet/multi-contact-release"
        other-gpg-keys: "0x892EA6EE273707C6495A6FB6220D644C64666806"
    - uses: actions/upload-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
        path: /tmp/packages-${{ matrix.dist }}-${{ matrix.arch }}/
  # This job upload binary packages for Ubuntu
  upload-packages:
    needs: build-packages
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        dist: [xenial, bionic, focal]
        arch: [i386, amd64]
        exclude:
          - dist: focal
            arch: i386
    runs-on: ubuntu-18.04
    steps:
    - name: Download packages
      uses: actions/download-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
    - name: Upload to multi-contact-head
      uses: jrl-umi3218/github-actions/upload-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        subject: gergondet
        repo: multi-contact-head
        package: |
          name: openhrp3
          desc: "OpenHRP3 is an integrated software platform for robot simulations"
          licenses: [EPL-1.0]
          vcs_url: http://www.openrtp.jp/openhrp3/en/index.html
        version: 3.1.9
        path: packages-${{ matrix.dist }}-${{ matrix.arch }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Upload to multi-contact-release
      uses: jrl-umi3218/github-actions/upload-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        subject: gergondet
        repo: multi-contact-release
        package: |
          name: openhrp3
          desc: "OpenHRP3 is an integrated software platform for robot simulations"
          licenses: [EPL-1.0]
          vcs_url: http://www.openrtp.jp/openhrp3/en/index.html
        version: 3.1.9
        path: packages-${{ matrix.dist }}-${{ matrix.arch }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Request mirror sync
      run: |
        curl -ugergondet:${{ secrets.BINTRAY_API_KEY }} --header "X-GPG-PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}" -X POST https://api.bintray.com/calc_metadata/gergondet/multi-contact-head
        curl -ugergondet:${{ secrets.BINTRAY_API_KEY }} --header "X-GPG-PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}" -X POST https://api.bintray.com/calc_metadata/gergondet/multi-contact-release
    - name: Trigger dependents rebuild
      run: |
        curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.GH_PAGES_TOKEN }}" --request POST --data "{\"event_type\": \"package\"}" https://api.github.com/repos/gergondet/hrpsys-base/dispatches
